## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 26,  54,  73,  77, 131, 119,  10, 105, 146,  23,   9,   3,  49,
        65,   1,  22, 120,  46, 130,  62, 116,  55, 110, 127,  74, 138,
       109,  31,  20,  44, 132,  42, 107,   2,  38,  59,  14, 135, 126,
       103,  39,  47,  58,  79,   6,  93,  75,  72,  66, 143,  99, 114,
        61, 149,  32,  91,  78,  25,  45,  87,  50, 144,   5, 142,  57,
       147, 104, 128,  89,  95, 134, 141,  69,  83,  29, 111,  63,  41,
       122,  15,  94,  70,  18, 137, 101,  16,  96,  30,  53, 129, 124,
        37,  97,  82, 133, 139,  60,  43,  64,  28,  36,  35,   0,  86,
       121,   7,   4,  81,   8,  19,  68,  13, 102,  21,  98, 115, 118,
        51, 140, 112,  11,  92,  84,  33, 123,  27, 100,  56, 136,  40,
       106,  88,  12, 148,  76, 113,  90,  52,  67,  71,  17,  48, 125,
        80, 145, 117, 108,  24,  34,  85])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [18]:
y_predict

array([1, 2, 0, 1, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 2, 2, 2, 0, 0])

In [19]:
y_test

array([1, 2, 0, 1, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 2, 0, 1, 2, 0, 1, 0, 1, 0,
       0, 0, 2, 2, 2, 0, 0])

In [20]:
sum(y_predict == y_test)

29

In [21]:
sum(y_predict == y_test) / len(y_test)

0.96666666666666667

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split>

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
